const defaultRates = [{
        bankName: "Bank of Mauritius",
        productName: "Key Rate",
        category: "Benchmark",
        rate: 4.75,
        displayRate: "4.75%",
        rateType: "Policy benchmark",
        conditions: "Key Rate as published by Bank of Mauritius",
        sourceURL: "https://www.bom.mu/repo-rate",
        dateCollected: "2026-05-20",
        notes: "Official Bank of Mauritius online webpage source."
    },
    {
        bankName: "Absa Bank Mauritius",
        productName: "Personal Loan",
        category: "Loan",
        rate: 7.25,
        displayRate: "From 7.25% p.a.",
        rateType: "Indicative / from rate",
        conditions: "Subject to assessment against lending criteria",
        sourceURL: "https://www.absabank.mu/en/personal/get-a-personal-loan/",
        dateCollected: "2026-07-13",
        notes: "Advertised online rate may differ after bank assessment."
    },
    {
        bankName: "Absa Bank Mauritius",
        productName: "Home Loan",
        category: "Loan",
        rate: 5.30,
        displayRate: "As low as 5.30% p.a.",
        rateType: "Campaign / indicative",
        conditions: "Subject to eligibility and bank assessment",
        sourceURL: "https://www.absabank.mu/en/personal/get-a-home-loan/",
        dateCollected: "2026-07-13",
        notes: "Campaign rates may require bank confirmation."
    },
    {
        bankName: "MauBank",
        productName: "Personal Loan Calculator",
        category: "Loan",
        rate: 10.00,
        displayRate: "10.00%",
        rateType: "Calculator rate",
        conditions: "Minimum salary and repayment-capacity conditions apply",
        sourceURL: "https://maubank.mu/retail/loans/personal-loan-unsecured/",
        dateCollected: "2026-07-13",
        notes: "Calculator is for information only."
    },
    {
        bankName: "MCB",
        productName: "Personal Loan",
        category: "Loan",
        rate: 9.50,
        displayRate: "Indicative",
        rateType: "Personalised details",
        conditions: "Subject to income, debt and history with MCB",
        sourceURL: "https://mcb.mu/personal/loans/personal-loan",
        dateCollected: "2026-07-13",
        notes: "Website invites users to get personalised loan details."
    },
    {
        bankName: "SBM Bank Mauritius",
        productName: "Personal Loan",
        category: "Loan",
        rate: 5.10,
        displayRate: "As from 5.10% p.a.",
        rateType: "Indicative / from rate",
        conditions: "Terms apply; may depend on security and repayment capacity",
        sourceURL: "https://banking.sbmgroup.mu/individual/loans/personal-loan",
        dateCollected: "2026-07-21",
        notes: "Official product page indicates an as-from rate."
    },
    {
        bankName: "SBM Bank Mauritius",
        productName: "Consumer Loan Calculator / PLR",
        category: "Loan",
        rate: 7.10,
        displayRate: "PLR currently 7.10%",
        rateType: "Calculator benchmark",
        conditions: "Calculator input; check bank confirmation",
        sourceURL: "https://banking.sbmgroup.mu/individual/loans/boost-loan/calculator-consumer",
        dateCollected: "2026-07-21",
        notes: "Official calculator mentions PLR currently at 7.10%."
    },
    {
        bankName: "SBI Mauritius",
        productName: "Loans and Advances",
        category: "Loan",
        rate: null,
        displayRate: "Attractive rates",
        rateType: "No fixed numeric rate",
        conditions: "Contact bank / check product details",
        sourceURL: "https://mu.statebank/loans-and-advances",
        dateCollected: "2026-07-21",
        notes: "No clear numeric rate exposed in accessible page text."
    },
    {
        bankName: "Absa Bank Mauritius",
        productName: "Fixed Term Deposit Account",
        category: "Fixed Deposit",
        rate: null,
        displayRate: "Varies by term",
        rateType: "Fixed deposit / term-dependent",
        conditions: "Minimum deposit Rs50,000 for MUR fixed deposit; rate varies by term",
        sourceURL: "https://www.absabank.mu/en/personal/open-a-fixed-term-deposit-account/",
        dateCollected: "2026-07-24",
        notes: "Official webpage confirms rate varies by term."
    },
    {
        bankName: "MauBank",
        productName: "Fixed Deposit Account",
        category: "Fixed Deposit",
        rate: null,
        displayRate: "Check online source",
        rateType: "Fixed deposit",
        conditions: "Rate may depend on amount, currency and term",
        sourceURL: "https://maubank.mu/retail/day-to-day/fixed-deposit-account/",
        dateCollected: "2026-07-24",
        notes: "Check official product webpage before evaluation."
    },
    {
        bankName: "MCB",
        productName: "Fixed Deposit",
        category: "Fixed Deposit",
        rate: null,
        displayRate: "Check online source",
        rateType: "Fixed deposit",
        conditions: "Rate may depend on deposit term, amount and currency",
        sourceURL: "https://mcb.mu/personal/investments/fixed-deposit",
        dateCollected: "2026-07-24",
        notes: "Check official product webpage before evaluation."
    },
    {
        bankName: "SBM Bank Mauritius",
        productName: "Interest Rates Page",
        category: "Fixed Deposit",
        rate: null,
        displayRate: "Check online rate page",
        rateType: "Fixed deposit",
        conditions: "Rates vary by tenor and product conditions",
        sourceURL: "https://banking.sbmgroup.mu/individual/interest-rates",
        dateCollected: "2026-07-24",
        notes: "Check official SBM rate webpage."
    },
    {
        bankName: "SBI Mauritius",
        productName: "Interest, Service Charges and Fees",
        category: "Fixed Deposit",
        rate: null,
        displayRate: "Check online rate page",
        rateType: "Fixed deposit",
        conditions: "Rates vary by tenor and product conditions",
        sourceURL: "https://mu.statebank/interest-service-charges-and-fees",
        dateCollected: "2026-07-24",
        notes: "Check official SBI Mauritius rate/fees webpage."
    }
];
let bankRates = [...defaultRates];